# Generated by Django 4.0.6 on 2022-10-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='payment_closed',
        ),
    ]
