# Generated by Django 4.0.6 on 2022-10-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_postmodel_payment_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='lesson_week',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='lesson_time',
            field=models.TimeField(),
        ),
    ]
