# Generated by Django 4.0.6 on 2022-10-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('0', 'Teacher'), ('1', 'Student')], default='1', max_length=1),
        ),
    ]
